---
# https://docs.gitlab.com/ce/ci/yaml/README.html
# yamllint disable rule:line-length
image: docker:latest
services:
  - docker:dind

variables:
  GIT_DEPTH: "8"
  DOCKER_IMAGE: debian:unstable

build:
  script:
    - |
      docker pull "${DOCKER_IMAGE}"
      env | grep -E '^(TRAVIS_|BINTRAY_|GPG_|VIRUSTOTAL_|CODESIGN_|CC|GITLAB_|CI_)' > _env
      docker run -v "$(pwd):$(pwd)" -w "$(pwd)" \
        --env-file ./_env \
        "${DOCKER_IMAGE}" sh -c ./_ci_linux_debian.sh
  artifacts:
    paths:
      - public
  only:
    - master
    - dev-gitlab
    - test-gitlab
