# https://lint.travis-ci.org/
branches:
  only:
  - master
  - test-travis
language: c
env:
  - HB_CI_THREADS=4
os:
  - linux
  - osx
osx_image: xcode8.2
compiler:
  - i686-w64-mingw32-gcc
matrix:
  exclude:
    - os: osx
      compiler: gcc
sudo: false
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - binutils-mingw-w64
      - gcc-mingw-w64
      - wine
      - p7zip-full
before_install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update > /dev/null;
      brew install p7zip mingw-w64 jq osslsigncode dos2unix gpg
      brew cask install wine-devel
    fi
script:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      export PATH="/Applications/Wine Devel.app/Contents/Resources/wine/bin:${PATH}";
      export DISPLAY=:88.0; wineboot;
    fi;
    ./_build.sh;
notifications:
  email: false
git:
  submodules: false
  depth: 8
