version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\w\
environment:
  BINTRAY_APIKEY:
    secure: FUQVzdqjaAvLYH/yTdL1rdtrVcAheHbK4YUvNNpvArR09vfkkuAk+8ntrg2MRYa2
  BINTRAY_USER:
    secure: jfLq1ApyVLNouxv07skhrg==
  BINTRAY_PATH:
    secure: +CyA1IIhoPpI7EY54BsRADDxb1V62HDWLSekCX4mTxk=
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=
install:
- curl --version
- which curl
- set VER_ZLIB=1.2.8
- set VER_OPENSSL=1.0.2d
- set VER_LIBSSH2=1.6.0
- set VER_CURL=7.44.0
# Long URL: "https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/m/mi/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.1.0/threads-win32/sjlj/x86_64-5.1.0-release-win32-sjlj-rt_v4-rev0.7z" https://goo.gl/HF6raX
# Long URL: "https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/m/mi/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.1.0/threads-posix/sjlj/x86_64-5.1.0-release-posix-sjlj-rt_v4-rev0.7z"
- curl -fsS -L --proto-redir =https https://goo.gl/kS5jx4 -o mingw.7z
- openssl dgst -sha256 mingw.7z | findstr /i /c:"65b30e0469f03d0e219a1ebe022f135692ed6ecdaf4f9a86923ece7689157244"
# Will unpack into C:\w\mingw64
- 7z x -y -oC:\w\ mingw.7z > nul
- curl -fsS -L --proto-redir =https https://github.com/madler/zlib/archive/v%VER_ZLIB%.tar.gz -o zip.tar.gz
- openssl dgst -sha256 zip.tar.gz | findstr /i /c:"e380bd1bdb6447508beaa50efc653fe45f4edc1dafe11a251ae093e0ee97db9a"
- tar -zxvf zip.tar.gz > nul 2>&1
- del zip.tar.gz
- move zlib-%VER_ZLIB% zlib
- curl -fsS http://www.openssl.org/source/openssl-%VER_OPENSSL%.tar.gz -o openssl.tar.gz
- openssl dgst -sha256 openssl.tar.gz | findstr /i /c:"671c36487785628a703374c652ad2cebea45fa920ae5681515df25d9f2c9a8c8"
- tar -zxvf openssl.tar.gz > nul 2>&1
- del openssl.tar.gz
- move openssl-%VER_OPENSSL% openssl
- curl -fsS -L --proto-redir =https https://github.com/libssh2/libssh2/releases/download/libssh2-%VER_LIBSSH2%/libssh2-%VER_LIBSSH2%.tar.gz -o libssh2.tar.gz
- openssl dgst -sha256 libssh2.tar.gz | findstr /i /c:"5a202943a34a1d82a1c31f74094f2453c207bf9936093867f41414968c8e8215"
- tar -zxvf libssh2.tar.gz > nul 2>&1
- del libssh2.tar.gz
- move libssh2-%VER_LIBSSH2% libssh2
- curl -fsS -L --proto-redir =https https://github.com/bagder/curl/releases/download/curl-%VER_CURL:.=_%/curl-%VER_CURL%.tar.gz -o curl.tar.gz
- openssl dgst -sha256 curl.tar.gz | findstr /i /c:"d01212ee29110799db969be31eeab902f50eca00d52fb8fb44630d08964762be"
- tar -zxvf curl.tar.gz > nul 2>&1
- del curl.tar.gz
- move curl-%VER_CURL% curl
build_script:
- set _ORI_PATH=%PATH%
- set PATH=C:\w\mingw64\bin;%PATH%
- set CPU=win32
- mk-openssl.bat
- mk-libssh2.bat
- mk-curl.bat
- set CPU=win64
- mk-openssl.bat
- mk-libssh2.bat
- mk-curl.bat
