version: 1.0.{build}
skip_tags: true
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\w\
build:
  verbosity: detailed

environment:
  BINTRAY_APIKEY:
    secure: Awq2bXuEyT0/JC/phuGILqT9hj9sVslq2+btJlFhH89a1xagztNH8h3jTru5rJKd
  BINTRAY_USER:
    secure: jfLq1ApyVLNouxv07skhrg==
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Using zlib headers and static libraries bundled with mingw-w64
# - set VER_ZLIB=1.2.8
  - set VER_NGHTTP2=1.6.0
  - set VER_OPENSSL=1.0.2e
  - set VER_LIBRTMP=2.3
  - set VER_LIBSSH2=1.6.0
  - set VER_CURL=7.46.0
  - python -m pip --disable-pip-version-check install --upgrade pip
  - python -m pip install pefile
  # PATH must be reconfigured to use short name for the sh.exe location, otherwise the OpenSSL build process fails
  - set PATH=C:\PROGRA~1\Git\usr\bin;%PATH%
  - sh -c ./dl.sh

build_script:
  - set PATH=%APPVEYOR_BUILD_FOLDER%\mingw64\bin;%PATH%
  - set _MAK=%APPVEYOR_BUILD_FOLDER%\mingw64\bin\mingw32-make.exe
  - set CPU=win32
  - sh -c "./mk-nghttp2.sh %VER_NGHTTP2% %CPU%"
  - sh -c "./mk-openssl.sh %VER_OPENSSL% %CPU%"
# - sh -c "./mk-librtmp.sh %VER_LIBRTMP% %CPU%"
  - sh -c "./mk-libssh2.sh %VER_LIBSSH2% %CPU%"
  - sh -c "./mk-curl.sh    %VER_CURL%    %CPU%"
  - set CPU=win64
  - sh -c "./mk-nghttp2.sh %VER_NGHTTP2% %CPU%"
  - sh -c "./mk-openssl.sh %VER_OPENSSL% %CPU%"
# - sh -c "./mk-librtmp.sh %VER_LIBRTMP% %CPU%"
  - sh -c "./mk-libssh2.sh %VER_LIBSSH2% %CPU%"
  - sh -c "./mk-curl.sh    %VER_CURL%    %CPU%"
  - type hashes.txt
