version: 1.0.{build}
skip_tags: true
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\w\
build:
  verbosity: detailed

environment:
  BINTRAY_APIKEY:
    secure: Awq2bXuEyT0/JC/phuGILqT9hj9sVslq2+btJlFhH89a1xagztNH8h3jTru5rJKd
  BINTRAY_USER:
    secure: jfLq1ApyVLNouxv07skhrg==
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=

  ZLIB_VER_: 1.2.8
  ZLIB_HASH: e380bd1bdb6447508beaa50efc653fe45f4edc1dafe11a251ae093e0ee97db9a
  NGHTTP2_VER_: 1.6.0
  NGHTTP2_HASH: 7ac5624bc744c766bf6b37de31d7c48dfceb648313306311943968bdad77d5bd
  OPENSSL_VER_: 1.0.2e
  OPENSSL_HASH: e23ccafdb75cfcde782da0151731aa2185195ac745eea3846133f2e05c0e0bff
  LIBRTMP_VER_: 2.3
  LIBRTMP_HASH: ef38b7a99d82ce6912063d21063aeaf28185341b3df486e24bffce5354224b2c
  LIBSSH2_VER_: 1.6.0
  LIBSSH2_HASH: 5a202943a34a1d82a1c31f74094f2453c207bf9936093867f41414968c8e8215
  CURL_VER_: 7.46.0
  CURL_HASH: b7d726cdd8ed4b6db0fa1b474a3c59ebbbe4dcd4c61ac5e7ade0e0270d3195ad

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - python -m pip --disable-pip-version-check install --upgrade pip
  - python -m pip install pefile
  # PATH must be reconfigured to use short name for the sh.exe location, otherwise the OpenSSL build process fails.
  # It is also required to override Windows tools with Git for Windows ones. (f.e. 'find')
  - set PATH=C:\PROGRA~1\Git\usr\bin;%PATH%
  - sh -c ./dl.sh

build_script:
  - set PATH=%APPVEYOR_BUILD_FOLDER%\mingw64\bin;%PATH%
  - set _MAK=%APPVEYOR_BUILD_FOLDER%\mingw64\bin\mingw32-make.exe
  - set CPU=win32
  - sh -c "./mk-nghttp2.sh %NGHTTP2_VER_% %CPU%"
  - sh -c "./mk-openssl.sh %OPENSSL_VER_% %CPU%"
# - sh -c "./mk-librtmp.sh %LIBRTMP_VER_% %CPU%"
  - sh -c "./mk-libssh2.sh %LIBSSH2_VER_% %CPU%"
  - sh -c "./mk-curl.sh       %CURL_VER_% %CPU%"
  - set CPU=win64
  - sh -c "./mk-nghttp2.sh %NGHTTP2_VER_% %CPU%"
  - sh -c "./mk-openssl.sh %OPENSSL_VER_% %CPU%"
# - sh -c "./mk-librtmp.sh %LIBRTMP_VER_% %CPU%"
  - sh -c "./mk-libssh2.sh %LIBSSH2_VER_% %CPU%"
  - sh -c "./mk-curl.sh       %CURL_VER_% %CPU%"
  - type hashes.txt

artifacts:
  - path: nghttp2/nghttp2-*-win32-mingw*.7z
    name: nghttp2-mingw32
  - path: nghttp2/nghttp2-*-win64-mingw*.7z
    name: nghttp2-mingw64
  - path: openssl/openssl-*-win32-mingw*.7z
    name: openssl-mingw32
  - path: openssl/openssl-*-win64-mingw*.7z
    name: openssl-mingw64
  - path: libssh2/libssh2-*-win32-mingw*.7z
    name: libssh2-mingw32
  - path: libssh2/libssh2-*-win64-mingw*.7z
    name: libssh2-mingw64
  - path: curl/curl-*-win32-mingw*.7z
    name: curl-mingw32
  - path: curl/curl-*-win64-mingw*.7z
    name: curl-mingw64
