version: 1.0.{build}
skip_tags: true
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\w\
build:
  verbosity: detailed

environment:
  BINTRAY_APIKEY:
    secure: Awq2bXuEyT0/JC/phuGILqT9hj9sVslq2+btJlFhH89a1xagztNH8h3jTru5rJKd
  BINTRAY_USER:
    secure: jfLq1ApyVLNouxv07skhrg==
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=

  ZLIB_VER_: 1.2.8
  ZLIB_HASH: e380bd1bdb6447508beaa50efc653fe45f4edc1dafe11a251ae093e0ee97db9a
  NGHTTP2_VER_: 1.7.0
  NGHTTP2_HASH: 9447ddfc2888c5d2d7ef27370b9f911c0263430666682105ca4066dcd88708f0
  OPENSSL_VER_: 1.0.2f
  OPENSSL_HASH: 932b4ee4def2b434f85435d9e3e19ca8ba99ce9a065a61524b429a9d5e9b2e9c
  LIBRTMP_VER_: 2.3
  LIBRTMP_HASH: ef38b7a99d82ce6912063d21063aeaf28185341b3df486e24bffce5354224b2c
  LIBSSH2_VER_: 1.6.0
  LIBSSH2_HASH: 5a202943a34a1d82a1c31f74094f2453c207bf9936093867f41414968c8e8215
  CURL_VER_: 7.47.0
  CURL_HASH: 2b096f9387fb9b2be08d17e518c62b6537b1f4d4bb59111d5b4fa0272f383f66

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - python -m pip --disable-pip-version-check install --upgrade pip
  - python -m pip install pefile
  # PATH must be reconfigured to use short name for the sh.exe location, otherwise the OpenSSL build process fails.
  # It is also required to override Windows tools with Git for Windows ones. (f.e. 'find')
  - set PATH=C:\PROGRA~1\Git\usr\bin;%PATH%
  - sh -c ./_dl.sh

build_script:
  - set PATH=%APPVEYOR_BUILD_FOLDER%\mingw64\bin;%PATH%
  - set _MAK=%APPVEYOR_BUILD_FOLDER%\mingw64\bin\mingw32-make.exe
  - set _URL=https://github.com/%APPVEYOR_REPO_NAME%
  - set CPU=win32
  - sh -c "./nghttp2.sh %NGHTTP2_VER_% %CPU%"
  - sh -c "./openssl.sh %OPENSSL_VER_% %CPU%"
# - sh -c "./librtmp.sh %LIBRTMP_VER_% %CPU%"
  - sh -c "./libssh2.sh %LIBSSH2_VER_% %CPU%"
  - sh -c "./curl.sh       %CURL_VER_% %CPU%"
  - set CPU=win64
  - sh -c "./nghttp2.sh %NGHTTP2_VER_% %CPU%"
  - sh -c "./openssl.sh %OPENSSL_VER_% %CPU%"
# - sh -c "./librtmp.sh %LIBRTMP_VER_% %CPU%"
  - sh -c "./libssh2.sh %LIBSSH2_VER_% %CPU%"
  - sh -c "./curl.sh       %CURL_VER_% %CPU%"
  - type hashes.txt

artifacts:
  - path: nghttp2-*-mingw.*
  - path: openssl-*-mingw.*
  - path: librtmp-*-mingw.*
  - path: libssh2-*-mingw.*
  - path: curl-*-mingw.*
